# This is a basic workflow to help you get started with Actions

name: Artifact Upload Challenge

# Controls when the workflow will run
on: push
env: 
  ARTIFACT_NAME: my-artifact

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line Linux script
        run: date -u
  windows-job:
    runs-on: windows-latest
    steps:
      - name: Run a one-line Windows script
        run: date -u
  macos-job:
    runs-on: macos-latest
    steps:
      - name: Run a one-line Mac script
        run: date -u
  dependent-job:
    runs-on: ubuntu-latest
    needs: [ubuntu-job, windows-job, macos-job]
    steps:
      - name: Run it again
        run: date -u
