name: CI-CD Challenge

on: push
env: 
  ARTIFACT_NAME: my-artifact

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-and-run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: run python
        run: python ./hello.py
        
  checkout-and-create-artifact:
    runs-on: ubuntu-latest
    needs: checkout-and-run-python
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.my-artifact }}
          path: ./hello.py
 
