# This is a basic workflow to help you get started with Actions

name: Artifact Upload Challenge

# Controls when the workflow will run
on: push
env: 
  ARTIFACT_NAME: my-artifact

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Create Dummy File
        run: echo 'hey' > ${{ env.ARTIFACT_NAME }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dummy
          path: ./${{ env.ARTIFACT_NAME }}
      
